version: '3.8'

services:
  web:
    build:
      context: web
      target: ui-build
    ports:
      - '80:80'
    restart: always

  server:
    build:
      context: server
      args:
        STAGE: build
      target: server
    restart: always

  cacher:
    restart: always
