version: '3.8'

services:
  web:
    build:
      context: web
      target: ui-build
    ports:
      - '80:80'
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  server:
    build:
      context: server
      target: server-build
    restart: always

  server-proxy:
    restart: always

  cacher:
    restart: always

  database:
    env_file:
      - .env.prod
    restart: unless-stopped

  database-admin:
