version: '3.8'

services:
  web:
    build:
      context: web
      target: ui-build
    restart: always

  server:
    build:
      context: server
      target: server-build
    restart: always

  cacher:
    restart: always
